#!/bin/bash

# Bulk GPT E2E Test Execution Script
# Manual verification helper for critical user flows

echo "🧪 Bulk GPT E2E Test Suite - Manual Verification Helper"
echo "========================================================="
echo ""
echo "Server Status:"
echo "--------------"

# Check if server is running
if lsof -i :5005 > /dev/null 2>&1; then
    echo "✅ Server running on port 5005"
else
    echo "❌ Server NOT running on port 5005"
    echo "   Start with: cd bulk-gpt-app && PORT=5005 npm run dev"
    exit 1
fi

echo ""
echo "Testing server response..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5005/auth)
if [ "$HTTP_CODE" -eq 200 ]; then
    echo "✅ Auth page accessible (HTTP $HTTP_CODE)"
else
    echo "⚠️  Auth page returned HTTP $HTTP_CODE"
fi

echo ""
echo "📋 Manual Test Checklist (Open in Browser)"
echo "==========================================="
echo ""
echo "🌐 Open: http://localhost:5005/auth"
echo ""
echo "TEST 1: Authentication"
echo "----------------------"
echo "1. ☐ Page loads without errors"
echo "2. ☐ Title: 'Welcome to Bulk GPT' visible"
echo "3. ☐ Email and password inputs present"
echo "4. ☐ Demo credentials shown: test@example.com / password"
echo "5. ☐ Enter demo credentials"
echo "6. ☐ Click 'Sign in'"
echo "7. ☐ Redirects to /wizard"
echo ""

echo "TEST 2: Wizard Step 1 - Upload"
echo "-------------------------------"
echo "8. ☐ Step 1 indicator active"
echo "9. ☐ FileSpreadsheet icon visible (larger than before)"
echo "10. ☐ Dropzone shows 'Upload CSV File'"
echo "11. ☐ 'Browse Files' button is primary blue (not outline)"
echo "12. ☐ File limits shown: 'Max 50MB • Up to 10,000 rows • .CSV format'"
echo "13. ☐ Drag test-data.csv onto dropzone"
echo "14. ☐ During drag: border turns blue, scale increases, text changes"
echo "15. ☐ After drop: Loader2 spinning icon appears"
echo "16. ☐ Parse completes: Shows '5 rows • 4 columns'"
echo "17. ☐ Preview table displays correctly"
echo "18. ☐ 'Next' button enabled"
echo "19. ☐ Click 'Next'"
echo ""

echo "TEST 3: Wizard Step 2 - Configure"
echo "----------------------------------"
echo "20. ☐ Step 2 indicator active"
echo "21. ☐ Filename shown: 'test-data.csv'"
echo "22. ☐ Row count shown: '5 rows'"
echo "23. ☐ Blue hint box visible: 'Use variables in your prompt'"
echo "24. ☐ Lists available columns in hint"
echo "25. ☐ Prompt textarea visible"
echo "26. ☐ Column pills shown: name, email, company, title"
echo "27. ☐ Processing mode cards visible (2 cards side-by-side)"
echo "28. ☐ Test Mode card shows: row count, time estimate (~15 sec), cost (<\$0.01)"
echo "29. ☐ Full Processing card shows: 5 rows, time, cost"
echo "30. ☐ Enter prompt with invalid variable: 'Hello {{invalid}}'"
echo "31. ☐ Textarea border turns RED immediately"
echo "32. ☐ Error icon (AlertCircle) appears"
echo "33. ☐ Error message: 'Variable not found in CSV'"
echo "34. ☐ Shows available columns"
echo "35. ☐ 'Next' button disabled"
echo "36. ☐ Clear and enter valid prompt: 'Write email to {{name}} at {{company}}'"
echo "37. ☐ Border returns to normal"
echo "38. ☐ Error disappears"
echo "39. ☐ Click 'name' pill - inserts {{name}} at cursor"
echo "40. ☐ Click Test Mode card"
echo "41. ☐ Card gets blue border and checkmark icon"
echo "42. ☐ Click Full Processing card to switch"
echo "43. ☐ Selection indicator moves"
echo "44. ☐ Select Test Mode again"
echo "45. ☐ 'Next' button enabled"
echo "46. ☐ Click 'Next'"
echo ""

echo "TEST 4: Wizard Step 3 - Results"
echo "--------------------------------"
echo "47. ☐ Step 3 indicator active"
echo "48. ☐ Processing starts (loading indicator)"
echo "49. ☐ Progress updates shown"
echo "50. ☐ Wait for completion (max 60 seconds)"
echo "51. ☐ Results table appears with 3 columns: Input, Output, Status"
echo "52. ☐ Input column shows formatted data: 'John Doe • Acme Inc' (NOT '{}')"
echo "53. ☐ Output column shows generated content (NOT generic error)"
echo "54. ☐ Status badges visible: green with checkmark or red with X"
echo "55. ☐ If any failed: error message is SPECIFIC (not 'No output - failed to generate')"
echo "56. ☐ Summary statistics shown: Total, Completed, Failed, Success Rate"
echo "57. ☐ 'Export CSV' button visible"
echo "58. ☐ Click 'Export CSV'"
echo "59. ☐ File downloads successfully"
echo "60. ☐ Open CSV: contains input + output + status"
echo "61. ☐ 'Copy to Clipboard' button visible"
echo "62. ☐ Click 'Copy to Clipboard'"
echo "63. ☐ Success message appears: 'Copied to clipboard'"
echo "64. ☐ 'Restart' button visible"
echo "65. ☐ Click 'Restart'"
echo "66. ☐ Redirects back to Step 1"
echo ""

echo "TEST 5: Navigation"
echo "------------------"
echo "67. ☐ Upload CSV again"
echo "68. ☐ Go to Step 2"
echo "69. ☐ Click Step 1 indicator in nav"
echo "70. ☐ Returns to Step 1"
echo "71. ☐ CSV data preserved"
echo "72. ☐ Click 'Next' to return to Step 2"
echo "73. ☐ Configuration preserved"
echo "74. ☐ Click 'Back' button"
echo "75. ☐ Returns to Step 1"
echo ""

echo "TEST 6: Visual Improvements"
echo "---------------------------"
echo "76. ☐ Upload UX: FileSpreadsheet icon is 64px (not 48px)"
echo "77. ☐ Upload UX: Scale animation on drag hover"
echo "78. ☐ Upload UX: Browse button is solid blue (not outline)"
echo "79. ☐ Configure: Hint component has blue background with icon"
echo "80. ☐ Configure: Processing cards have proper elevation/shadow"
echo "81. ☐ Configure: Selected card has blue border + checkmark"
echo "82. ☐ Configure: Time and cost estimates visible"
echo "83. ☐ Results: Input shows actual data (name • company), not {}"
echo "84. ☐ Results: Errors are specific, not generic"
echo "85. ☐ Overall: No console errors"
echo ""

echo "TEST 7: Responsive Design"
echo "-------------------------"
echo "86. ☐ Resize to 375px (mobile)"
echo "87. ☐ Layout not broken"
echo "88. ☐ Processing cards stack vertically"
echo "89. ☐ Resize to 768px (tablet)"
echo "90. ☐ Layout adjusts appropriately"
echo "91. ☐ Resize to 1920px (desktop)"
echo "92. ☐ Content properly centered"
echo ""

echo "TEST 8: Accessibility"
echo "---------------------"
echo "93. ☐ Tab through all interactive elements"
echo "94. ☐ Focus visible on each element"
echo "95. ☐ Can complete entire flow with keyboard only"
echo "96. ☐ Error inputs have aria-invalid"
echo "97. ☐ All buttons have proper labels"
echo ""

echo "TEST 9: Edge Cases"
echo "------------------"
echo "98. ☐ Upload empty CSV (only headers)"
echo "99. ☐ Appropriate error shown"
echo "100. ☐ Upload test-special-chars.csv"
echo "101. ☐ Special characters display correctly"
echo "102. ☐ Unicode and emoji preserved"
echo ""

echo "✅ COMPLETION CHECKLIST"
echo "======================="
echo ""
echo "Critical Features (Must Pass):"
echo "- [ ] All 6 SaaS improvements visible"
echo "- [ ] Real-time validation works"
echo "- [ ] Error messages are specific"
echo "- [ ] Input data displays correctly (not {})"
echo "- [ ] Processing mode shows estimates"
echo "- [ ] Upload UX enhancements visible"
echo "- [ ] Contextual help present"
echo ""
echo "Quality Checks:"
echo "- [ ] No console errors"
echo "- [ ] No visual glitches"
echo "- [ ] All features functional"
echo "- [ ] Performance acceptable"
echo ""

echo "📊 Test Coverage"
echo "================"
echo "Authentication:        7 checks"
echo "Upload (Step 1):      12 checks"
echo "Configure (Step 2):   27 checks"
echo "Results (Step 3):     20 checks"
echo "Navigation:            9 checks"
echo "Visual Improvements:  10 checks"
echo "Responsive:            7 checks"
echo "Accessibility:         5 checks"
echo "Edge Cases:            5 checks"
echo "------------------------"
echo "TOTAL:               102 checks"
echo ""
echo "✨ Happy Testing! ✨"



